---
driver:
  name: ssh_gzip
# set to ssh private key
  ssh_key: spec/test.pem
  username: centos
  sudo: true

provisioner:
  name: puppet_apply
  platform: centos
  manifests_path:  manifests
  modules_path: modules_mycompany
  hiera_data_path: hieradata
  require_puppet_repo: true
  require_chef_for_busser: false
  facter_file: facter/kitchen.rb
  librarian_puppet_ssl_file: 'C:/repository/puppet_repo/cacert.pem'
  puppet_debug: true
  puppet_verbose: true
  ignored_paths_from_root: []
  puppet_detailed_exitcodes: true

platforms:
  - name: centos-7.0

verifier:
  name: serverspec
# set to true to run serverspec on your workstation
#  remote_exec: false

suites:
  - name: base
    provisioner:
      custom_facts:
        role_name1: mycompany_base
        role_name2: mycompany_webserver
    verifier:
      patterns:
      - modules/mycompany_base/spec/acceptance/base_spec.rb
      env_vars:
        TARGET_HOST: 127.0.0.1
        LOGIN_USER: centos
        SUDO: true
# set to ssh private key
        SSH_KEY: spec/test.pem
